### ISSUE TITLE
[Feat] 소셜 로그인 기능 구현

### ISSUE THREAD

**Issue by lhaerim** [APPS-sookmyung/2024-WELLET-Server#12]
## 📌 Issue

웹 소셜 로그인 기능 구현
소셜 로그인은 카카오 로그인으로 진행
oauth, webclient, jwt 등등을 활용할 예정

![image](https://github.com/user-attachments/assets/82f2da3a-e055-4b1f-a6f0-1b9ef12f99bf)

---

## 📌 TODO
* [x] 애플리케이션 생성
* [x] 동의 항목 설정
* [x] RedirectURI 등록
* [x] 의존성 추가
* [x] 로그인 페이지 생성
* [x] Page Controller
* [x] KakaoLoginController
* [x] KakaoService
* [ ] HTTPS 인증서 발급

**Comment by lhaerim** [comment]
처음엔 SSL 인증서 없이 https uri로 접속을 하려니 보안상의 문제로 로그인이 불가하였다. 그리하여 내가 찾았던 방법은
1. Self-signed SSL 인증서 생성 
2. ngrok 도구 사용
등이 있었는데 둘 다 로컬 환경에 적합한 방안이었다.
현재 나는 ngrok 도구 사용을 하였는데 실제 프로덕션에서의 활용을 위해 HTTPS 인증서 발급받을 예정이다
