### ISSUE TITLE
[Fix] 명함 관련 디테일 수정

### ISSUE THREAD

**Issue by ajung7038** [APPS-sookmyung/2024-WELLET-Server#32]
## 📌 Issue

명함 관련 디테일 수정

---

## 📌 TODO
* [x]  명함 동시 삭제
* [x]  명함 추가할 때 그룹 넣기 (없으면 null)
* [x] 명함 추가 시 카테고리명 추가
* [x]  명함 저장 시 멤버 넣기
* [x] 명함 전체 조회 total 추가
* [x] 명함 전체 조회 시 id 추가
* [x] 명함 개별 조회, 전체 조회 시 날짜 추가
