### ISSUE TITLE
[Feat] 그룹 관련 디테일 수정

### ISSUE THREAD

**Issue by lhaerim** [APPS-sookmyung/2024-WELLET-Server#36]
## 📌 Issue

---

## 📌 TODO
* [x] dto 이름 변경
* [x]  cardName, cardCompany 관련 엔티티 수정
* [x]  categoryCard add 부분 CategoryCardService로 빼기
* [x]  그룹 명함 조회 → 리스트로 전달
* [x]  category 삭제 로직 짜기
* [x]  트랜잭션으로 묶기 (catgory 생성/수정/삭제)
